#!/usr/bin/env python3
# coding=utf-8

'''taskcoach-category-efforts
'''

from os import environ
from os.path import pathsep
from datetime import datetime, timedelta

from pysyspol.taskcoach import get_category_efforts, DEFAULT_DATETIME_FMT

TASKCOACH_FP = environ['SYSPOL_TASKCOACH_FP'].split(pathsep)
CATEGORIES = environ['SYSPOL_TASKCOACH_DEFAULT_CATEGORIES'].split()
START = datetime.strptime(environ['SYSPOL_TASKCOACH_DEFAULT_START'],
        DEFAULT_DATETIME_FMT)
try:
    END = datetime.strptime(environ['SYSPOL_TASKCOACH_DEFAULT_END'],
            DEFAULT_DATETIME_FMT)
except ValueError:
    END = None

out = [(category, effort) for category, effort in
        get_category_efforts(CATEGORIES, START, END, paths=TASKCOACH_FP)]
total_effort = sum(record[1] for record in out)
out = [(category, effort, effort / total_effort) for category, effort in out]

for record in out:
    print('\t'.join(str(i) for i in record))

# vim: ft=python
