#!/usr/bin/env python
# coding=utf-8

'''randomize-basename'''

# Standard library imports.
from __future__ import division
from pprint import pprint
from argparse import ArgumentParser
import sys
import os
import atexit
import gc

# Related third party imports.
# import third_party_mod

# Local application/library specific imports.
# import app_specific_mod

# Relevant ``__all__`` specification here.
# __all__ = ...

# GLOBAL CONSTANT names.  *if main* section at bottom sets global names too.

def on_exit():
    '''Actions to do on exit.'''
    #print('on_exit', LOGF)

    # Invoke the garbage collector.
    gc.collect()

def main():
    parser = ArgumentParser()
    parser.add_argument('filename_src', nargs='*',
            help='''Regular file or directory''')
    args = parser.parse_args()

    for fname in args.filename_src:
        fname_dirname, fname_basename = os.path.split(fname)

if __name__ == "__main__":
    # Program name from file name.
    PN = os.path.splitext(sys.argv[0])[0]

    # Log file.
    LOGF = ''.join([PN, '_log', '.txt'])

    atexit.register(on_exit)

    main()
